fix: 修复剧照预览页(StillActivity)启动崩溃
详情页点击剧照查看大图并设置桌面壁纸时，Activity 启动即崩溃：
  java.lang.ClassNotFoundException: Didn't find class "android.view.LinearLayoutCompat"
  Caused by: InflateException: Binary XML file line #22: Error inflating class LinearLayoutCompat

原因：activity_still.xml 中 <LinearLayoutCompat> 写成了不带包名的裸类名，
LayoutInflater 会默认补上 android.view. 前缀，去查找并不存在的
android.view.LinearLayoutCompat，构造 View 时直接抛 ClassNotFoundException。

修复：改为全限定类名 androidx.appcompat.widget.LinearLayoutCompat，
与仓库内其他布局(view_widget_vod.xml 等)的写法保持一致。